"""Generated by tools/generate_compat_tools.py; original signatures, SQLite behavior."""

from __future__ import annotations


def register(mcp, compatibility):
    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def preview_diagram(source: str) -> dict:
        """Structurally validate Mermaid text without a web frontend. This is a syntax heuristic, not a browser render.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("preview_diagram", source=source)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def workspace_health(project_id: str) -> dict:
        """Find notes needing review, broken links, orphan notes, old drafts and missing owners in a collection.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("workspace_health", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def mark_reviewed(note_id: str) -> dict:
        """Record that a note is still correct: sets `reviewed:` to today in its
        frontmatter and changes nothing else (editor+). Only call it after
        actually checking the content. Errors: `conflict` (the note changed
        meanwhile, so read it and retry), `frontmatter_invalid` (fix the YAML
        first).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("mark_reviewed", note_id=note_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_revisions(note_id: str) -> dict:
        """Version history for a note (newest first): id, trigger, label, author,
        timestamp. Bodies are fetched with `read_revision`.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_revisions", note_id=note_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def read_revision(note_id: str, revision_id: str) -> dict:
        """Fetch the full body of one past revision of a note.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("read_revision", note_id=note_id, revision_id=revision_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def restore_revision(note_id: str, revision_id: str) -> dict:
        """Roll a note's body back to a past revision (editor+). The current body
        is snapshotted first, so the restore is itself reversible.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "restore_revision", note_id=note_id, revision_id=revision_id
        )

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_tags(project_id: str) -> dict:
        """Tags used in a workspace with note counts, most-used first.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_tags", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def graph(project_id: str | None = None) -> dict:
        """Nodes + links of the knowledge graph. Pass `project_id` for a single
        workspace's note graph; omit it for the whole-account structure graph
        across every workspace you can see.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("graph", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_members(project_id: str) -> dict:
        """Members and pending invitations of a workspace, plus your own role.
        Any member may view. Member entries carry the user_id needed by
        `set_member_role` / `remove_member`.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_members", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def share_workspace(project_id: str, upn: str, role: str = "viewer") -> dict:
        """Grant a local token identity access by its configured UPN. Unknown identities create pending local invitations; no email is sent.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "share_workspace", project_id=project_id, upn=upn, role=role
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def set_member_role(project_id: str, user_id: str, role: str) -> dict:
        """Change a member's role (owner only).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "set_member_role", project_id=project_id, user_id=user_id, role=role
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def remove_member(project_id: str, user_id: str) -> dict:
        """Remove a member, or leave the workspace yourself (owner only for
        others; any member may remove themselves).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("remove_member", project_id=project_id, user_id=user_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def revoke_invitation(project_id: str, invitation_id: str) -> dict:
        """Revoke a pending local invitation before the matching token identity connects.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "revoke_invitation", project_id=project_id, invitation_id=invitation_id
        )

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_org_workspaces() -> dict:
        """List collections readable by all authenticated local token identities, without an explicit membership.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_org_workspaces")

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def read_note(note_id: str) -> dict:
        """Fetch a note's full body, frontmatter metadata and backlinks.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("read_note", note_id=note_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def create_note(
        project_id: str, title: str, body: str = "", folder_id: str | None = None
    ) -> dict:
        """Author a new markdown note in a workspace (editor+).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "create_note", project_id=project_id, title=title, body=body, folder_id=folder_id
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def update_note(
        note_id: str,
        title: str | None = None,
        body: str | None = None,
        base_updated_at: str | None = None,
    ) -> dict:
        """Edit a note's title and/or body (editor+). Re-embeds, re-parses links
        and snapshots the prior version automatically. Body is standard markdown,
        including ```mermaid diagram blocks (validate with `preview_diagram`).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "update_note", note_id=note_id, title=title, body=body, base_updated_at=base_updated_at
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def link_notes(note_id: str, target_title: str) -> dict:
        """Append a `[[wikilink]]` to `target_title` at the end of a note's body
        (editor+), then re-parse links so the edge (and its backlink) appears.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("link_notes", note_id=note_id, target_title=target_title)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def link_mention(note_id: str, source_note_id: str) -> dict:
        """Turn the first unlinked plain-text mention of note `note_id` inside
        note `source_note_id` into a `[[wikilink]]` (editor+ on the source; the
        target only needs read access). Find candidates with
        `unlinked_mentions`.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "link_mention", note_id=note_id, source_note_id=source_note_id
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def save_version(note_id: str, label: str | None = None) -> dict:
        """Snapshot a note's current body as a labelled version (editor+), so it
        can be restored later from history.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("save_version", note_id=note_id, label=label)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_projects() -> dict:
        """The workspaces (projects) you belong to, with your role in each.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_projects")

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def create_workspace(name: str) -> dict:
        """Create a new workspace (project) owned by you.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("create_workspace", name=name)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def rename_workspace(project_id: str, name: str) -> dict:
        """Rename a workspace (owner only).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("rename_workspace", project_id=project_id, name=name)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def set_workspace_access(project_id: str, org_access: str) -> dict:
        """Set visibility to none (members only) or viewer (all authenticated local token identities). Owner only.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "set_workspace_access", project_id=project_id, org_access=org_access
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def delete_workspace(project_id: str) -> dict:
        """Move a whole workspace to Trash (owner only). Recoverable with
        `restore`. The personal workspace can't be deleted.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("delete_workspace", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_tree(project_id: str) -> dict:
        """Folders and notes in a workspace — the whole tree in one call.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_tree", project_id=project_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def create_folder(project_id: str, name: str, parent_id: str | None = None) -> dict:
        """Create a folder in a workspace (editor+). `parent_id` nests it; omit
        for a top-level folder.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "create_folder", project_id=project_id, name=name, parent_id=parent_id
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def rename_folder(folder_id: str, name: str) -> dict:
        """Rename a folder (editor+).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("rename_folder", folder_id=folder_id, name=name)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def move(
        item_type: str,
        item_id: str,
        project_id: str | None = None,
        folder_id: str | None = None,
        parent_id: str | None = None,
    ) -> dict:
        """Move a note or folder within or across workspaces (editor+ in both).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "move",
            item_type=item_type,
            item_id=item_id,
            project_id=project_id,
            folder_id=folder_id,
            parent_id=parent_id,
        )

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def copy(item_type: str, item_id: str) -> dict:
        """Duplicate a note or folder in place (editor+).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("copy", item_type=item_type, item_id=item_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def delete(item_type: str, item_id: str) -> dict:
        """Move a note or folder to Trash (editor+). Recoverable with `restore`;
        a folder takes everything inside it. This is a soft delete — use `purge`
        to remove permanently.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("delete", item_type=item_type, item_id=item_id)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def search(query: str, project_id: str | None = None, limit: int = 20) -> dict:
        """Hybrid keyword + semantic search across every note you can access.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("search", query=query, project_id=project_id, limit=limit)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def grep(text: str, project_id: str | None = None, limit: int = 20) -> dict:
        """Find notes containing `text` exactly: case-insensitive and literal
        (not a regex, no stemming), across every note you can access. Use it
        for names, error codes, file paths, URLs and quotes; use `search` for
        questions about meaning.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("grep", text=text, project_id=project_id, limit=limit)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def query_notes(
        project_id: str | None = None,
        type: str | None = None,
        tags: list[str] | None = None,
        status: str | None = None,
        updated_by: str | None = None,
        limit: int = 50,
    ) -> dict:
        """List notes by structured metadata, most recently edited first (no
        relevance ranking).

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call(
            "query_notes",
            project_id=project_id,
            type=type,
            tags=tags,
            status=status,
            updated_by=updated_by,
            limit=limit,
        )

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def suggest_links(note_id: str, limit: int = 8) -> dict:
        """Semantically nearest notes to this one, in the same workspace — link
        candidates to propose. Excludes the note itself and notes it already
        links to. Empty until the note has been embedded. Pair with `link_notes`.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("suggest_links", note_id=note_id, limit=limit)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def unlinked_mentions(note_id: str, limit: int = 20) -> dict:
        """Notes in the same workspace that mention this note's title (or one of
        its frontmatter `aliases`) in plain text but don't link to it yet — the
        "someone wrote its name but forgot the [[wikilink]]" list.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("unlinked_mentions", note_id=note_id, limit=limit)

    @mcp.tool(annotations={"readOnlyHint": True, "destructiveHint": False, "openWorldHint": False})
    async def list_trash() -> dict:
        """Restorable items you can act on: your archived workspaces plus the
        delete-roots (top-level trashed notes/folders) in workspaces you edit.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("list_trash")

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": False, "openWorldHint": False})
    async def restore(item_type: str, item_id: str) -> dict:
        """Restore a trashed note, folder or workspace.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("restore", item_type=item_type, item_id=item_id)

    @mcp.tool(annotations={"readOnlyHint": False, "destructiveHint": True, "openWorldHint": False})
    async def purge(item_type: str, item_id: str) -> dict:
        """Permanently delete a trashed note, folder or workspace. Irreversible —
        there is no undo. Notes/folders need editor+, a workspace needs owner.

        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.
        """
        return await compatibility.call("purge", item_type=item_type, item_id=item_id)
