"""Generate explicit MCP wrappers retaining every upstream tool name and signature."""

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
READ = {
    "preview_diagram",
    "workspace_health",
    "list_revisions",
    "read_revision",
    "list_tags",
    "graph",
    "list_members",
    "list_org_workspaces",
    "read_note",
    "list_projects",
    "list_tree",
    "search",
    "grep",
    "query_notes",
    "suggest_links",
    "unlinked_mentions",
    "list_trash",
}


def generate():
    lines = [
        '"""Generated by tools/generate_compat_tools.py; original signatures, SQLite behavior."""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "def register(mcp, compatibility):",
    ]
    for path in sorted((ROOT / "upstream/src/tools").glob("*.py")):
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if not any(
                isinstance(d, ast.Call)
                and isinstance(d.func, ast.Attribute)
                and d.func.attr == "tool"
                for d in node.decorator_list
            ):
                continue
            signature = ast.unparse(node.args)
            doc = (ast.get_docstring(node) or node.name).split("\n\n")[0].replace('"""', "'''")
            if node.name in {
                "share_workspace",
                "list_org_workspaces",
                "set_workspace_access",
                "revoke_invitation",
            }:
                doc = {
                    "share_workspace": "Grant a local token identity access by its configured UPN. Unknown identities create pending local invitations; no email is sent.",
                    "list_org_workspaces": "List collections readable by all authenticated local token identities, without an explicit membership.",
                    "set_workspace_access": "Set visibility to none (members only) or viewer (all authenticated local token identities). Owner only.",
                    "revoke_invitation": "Revoke a pending local invitation before the matching token identity connects.",
                }[node.name]
            if node.name == "preview_diagram":
                doc = "Structurally validate Mermaid text without a web frontend. This is a syntax heuristic, not a browser render."
            if node.name == "workspace_health":
                doc = "Find notes needing review, broken links, orphan notes, old drafts and missing owners in a collection."
            annotations = {
                "readOnlyHint": node.name in READ,
                "destructiveHint": node.name == "purge",
                "openWorldHint": False,
            }
            arguments = ", ".join(f"{a.arg}={a.arg}" for a in node.args.args)
            lines += [
                f"    @mcp.tool(annotations={annotations!r})",
                f"    async def {node.name}({signature}) -> dict:",
                '        """'
                + doc.replace("\n", "\n        ")
                + '\n\n        HA re:call: notes are entity descriptions in SQLite. No web UI; returned URL fields are null. Local token grants replace SSO.\n        """',
                f'        return await compatibility.call("{node.name}"{", " if arguments else ""}{arguments})',
                "",
            ]
    (ROOT / "ha_recall/compat_tools.py").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate()
